// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebAPI.Entities.Entities;

/// <summary>
/// 库存修改日志表
/// </summary>
[Table("stock_log")]
[Index("CommodityId", Name = "idx_stock_log_commodity_id")]
[Index("CreateTime", Name = "idx_stock_log_create_time")]
[Index("UserId", Name = "idx_stock_log_user_id")]
public partial class StockLog
{
    /// <summary>
    /// 库存日志ID
    /// </summary>
    [Key]
    [Column("stock_log_id")]
    public int StockLogId { get; set; }

    /// <summary>
    /// 商品ID
    /// </summary>
    [Column("commodity_id")]
    public int CommodityId { get; set; }

    /// <summary>
    /// 库存变更数量
    /// </summary>
    [Column("change_quantity")]
    public int ChangeQuantity { get; set; }

    /// <summary>
    /// 变更前库存
    /// </summary>
    [Column("before_stock")]
    public int BeforeStock { get; set; }

    /// <summary>
    /// 变更后库存
    /// </summary>
    [Column("after_stock")]
    public int AfterStock { get; set; }

    /// <summary>
    /// 操作人用户ID
    /// </summary>
    [Column("user_id")]
    public int UserId { get; set; }

    /// <summary>
    /// 创建时间
    /// </summary>
    [Column("create_time", TypeName = "datetime")]
    public DateTime CreateTime { get; set; }
}